services:
    _defaults:
        autowire: true

    Sowieso\PhotoswipeBundle\Photoswipe\PhotoswipeList:
        class: Sowieso\PhotoswipeBundle\Photoswipe\PhotoswipeList

    Sowieso\PhotoswipeBundle\Twig\PhotoswipeRuntime:
        class: Sowieso\PhotoswipeBundle\Twig\PhotoswipeRuntime
        arguments:
            - '@request_stack'
            - '@contao.routing.scope_matcher'
            - '@Sowieso\PhotoswipeBundle\Photoswipe\PhotoswipeList'
        tags:
            - { name: "twig.runtime" }

    Sowieso\PhotoswipeBundle\Twig\PhotoswipeExtension:
        class: Sowieso\PhotoswipeBundle\Twig\PhotoswipeExtension
        tags:
            - { name: "twig.extension" }
